/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javademo_jni_AdemcoHbLibrary_ParseResult */

#ifndef _Included_javademo_jni_AdemcoHbLibrary_ParseResult
#define _Included_javademo_jni_AdemcoHbLibrary_ParseResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
