/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javademo_jni_AdemcoHbLibrary */

#ifndef _Included_javademo_jni_AdemcoHbLibrary
#define _Included_javademo_jni_AdemcoHbLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javademo_jni_AdemcoHbLibrary
 * Method:    nativePrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javademo_jni_AdemcoHbLibrary_nativePrint
  (JNIEnv *, jobject);

/*
 * Class:     javademo_jni_AdemcoHbLibrary
 * Method:    nativeParse
 * Signature: (Ljava/lang/String;I)Ljavademo/jni/AdemcoHbLibrary/ParseResult;
 */
JNIEXPORT jobject JNICALL Java_javademo_jni_AdemcoHbLibrary_nativeParse
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
