/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public enum AdemcoXDataTransform {
  AdemcoXDataTransform_as_is,
  AdemcoXDataTransform_to_ascii;

  public final int swigValue() {
    return swigValue;
  }

  public static AdemcoXDataTransform swigToEnum(int swigValue) {
    AdemcoXDataTransform[] swigValues = AdemcoXDataTransform.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AdemcoXDataTransform swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AdemcoXDataTransform.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AdemcoXDataTransform() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AdemcoXDataTransform(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AdemcoXDataTransform(AdemcoXDataTransform swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

