/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public enum AdemcoPacketId {
  AID_NULL,
  AID_ACK,
  AID_NAK,
  AID_DUH,
  AID_HB,
  AID_ADM_CID,
  AID_MOD_REG,
  AID_REG_RSP,
  AID_COUNT,
  AID_INVALID(libademcoJNI.AID_INVALID_get());

  public final int swigValue() {
    return swigValue;
  }

  public static AdemcoPacketId swigToEnum(int swigValue) {
    AdemcoPacketId[] swigValues = AdemcoPacketId.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AdemcoPacketId swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AdemcoPacketId.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AdemcoPacketId() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AdemcoPacketId(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AdemcoPacketId(AdemcoPacketId swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

