/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public class AdemcoDataSegment {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AdemcoDataSegment(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AdemcoDataSegment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libademcoJNI.delete_AdemcoDataSegment(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRaw(byte[] value) {
    libademcoJNI.AdemcoDataSegment_raw_set(swigCPtr, this, value);
  }

  public byte[] getRaw() {
    return libademcoJNI.AdemcoDataSegment_raw_get(swigCPtr, this);
  }

  public void setRaw_len(int value) {
    libademcoJNI.AdemcoDataSegment_raw_len_set(swigCPtr, this, value);
  }

  public int getRaw_len() {
    return libademcoJNI.AdemcoDataSegment_raw_len_get(swigCPtr, this);
  }

  public void setAdemcoId(long value) {
    libademcoJNI.AdemcoDataSegment_ademcoId_set(swigCPtr, this, value);
  }

  public long getAdemcoId() {
    return libademcoJNI.AdemcoDataSegment_ademcoId_get(swigCPtr, this);
  }

  public void setAdemcoEvent(AdemcoEvent value) {
    libademcoJNI.AdemcoDataSegment_ademcoEvent_set(swigCPtr, this, value.swigValue());
  }

  public AdemcoEvent getAdemcoEvent() {
    return AdemcoEvent.swigToEnum(libademcoJNI.AdemcoDataSegment_ademcoEvent_get(swigCPtr, this));
  }

  public void setGg(long value) {
    libademcoJNI.AdemcoDataSegment_gg_set(swigCPtr, this, value);
  }

  public long getGg() {
    return libademcoJNI.AdemcoDataSegment_gg_get(swigCPtr, this);
  }

  public void setZone(long value) {
    libademcoJNI.AdemcoDataSegment_zone_set(swigCPtr, this, value);
  }

  public long getZone() {
    return libademcoJNI.AdemcoDataSegment_zone_get(swigCPtr, this);
  }

  public AdemcoDataSegment() {
    this(libademcoJNI.new_AdemcoDataSegment(), true);
  }

}
