/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public class AdemcoPacket {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AdemcoPacket(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AdemcoPacket obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libademcoJNI.delete_AdemcoPacket(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCrc(int value) {
    libademcoJNI.AdemcoPacket_crc_set(swigCPtr, this, value);
  }

  public int getCrc() {
    return libademcoJNI.AdemcoPacket_crc_get(swigCPtr, this);
  }

  public void setLen(int value) {
    libademcoJNI.AdemcoPacket_len_set(swigCPtr, this, value);
  }

  public int getLen() {
    return libademcoJNI.AdemcoPacket_len_get(swigCPtr, this);
  }

  public void setId(AdemcoPacketId value) {
    libademcoJNI.AdemcoPacket_id_set(swigCPtr, this, value.swigValue());
  }

  public AdemcoPacketId getId() {
    return AdemcoPacketId.swigToEnum(libademcoJNI.AdemcoPacket_id_get(swigCPtr, this));
  }

  public void setSeq(int value) {
    libademcoJNI.AdemcoPacket_seq_set(swigCPtr, this, value);
  }

  public int getSeq() {
    return libademcoJNI.AdemcoPacket_seq_get(swigCPtr, this);
  }

  public void setAcct(String value) {
    libademcoJNI.AdemcoPacket_acct_set(swigCPtr, this, value);
  }

  public String getAcct() {
    return libademcoJNI.AdemcoPacket_acct_get(swigCPtr, this);
  }

  public void setData(AdemcoDataSegment value) {
    libademcoJNI.AdemcoPacket_data_set(swigCPtr, this, AdemcoDataSegment.getCPtr(value), value);
  }

  public AdemcoDataSegment getData() {
    long cPtr = libademcoJNI.AdemcoPacket_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AdemcoDataSegment(cPtr, false);
  }

  public void setXdata(AdemcoXDataSegment value) {
    libademcoJNI.AdemcoPacket_xdata_set(swigCPtr, this, AdemcoXDataSegment.getCPtr(value), value);
  }

  public AdemcoXDataSegment getXdata() {
    long cPtr = libademcoJNI.AdemcoPacket_xdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AdemcoXDataSegment(cPtr, false);
  }

  public void setTimestamp(SWIGTYPE_p_time_t value) {
    libademcoJNI.AdemcoPacket_timestamp_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getTimestamp() {
    return new SWIGTYPE_p_time_t(libademcoJNI.AdemcoPacket_timestamp_get(swigCPtr, this), true);
  }

  public void setRaw(byte[] value) {
    libademcoJNI.AdemcoPacket_raw_set(swigCPtr, this, value);
  }

  public byte[] getRaw() {
    return libademcoJNI.AdemcoPacket_raw_get(swigCPtr, this);
  }

  public void setRaw_len(int value) {
    libademcoJNI.AdemcoPacket_raw_len_set(swigCPtr, this, value);
  }

  public int getRaw_len() {
    return libademcoJNI.AdemcoPacket_raw_len_get(swigCPtr, this);
  }

  public AdemcoPacket() {
    this(libademcoJNI.new_AdemcoPacket(), true);
  }

}
