/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public enum HbCom_3sec_status {
  HbCom_3sec_arm(libademcoJNI.HbCom_3sec_arm_get()),
  HbCom_3sec_disarm(libademcoJNI.HbCom_3sec_disarm_get());

  public final int swigValue() {
    return swigValue;
  }

  public static HbCom_3sec_status swigToEnum(int swigValue) {
    HbCom_3sec_status[] swigValues = HbCom_3sec_status.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (HbCom_3sec_status swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + HbCom_3sec_status.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private HbCom_3sec_status() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private HbCom_3sec_status(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private HbCom_3sec_status(HbCom_3sec_status swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

