/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public enum HbMachineStatus {
  HMS_ARM,
  HMS_HALF_ARM,
  HMS_DISARM,
  HMS_SETTING,
  HMS_COUNT,
  HMS_INVALID(libademcoJNI.HMS_INVALID_get());

  public final int swigValue() {
    return swigValue;
  }

  public static HbMachineStatus swigToEnum(int swigValue) {
    HbMachineStatus[] swigValues = HbMachineStatus.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (HbMachineStatus swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + HbMachineStatus.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private HbMachineStatus() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private HbMachineStatus(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private HbMachineStatus(HbMachineStatus swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

