/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public enum HbZoneProperty {
  HZP_BUGLAR,
  HZP_EMERGENCY,
  HZP_FIRE,
  HZP_DURESS,
  HZP_GAS,
  HZP_WATER,
  HZP_SUB_MACHINE,
  HZP_REMOTE_CONTROL,
  HZP_BUGLAR_HALF,
  HZP_SHIELD,
  HZP_DOOR_RING,
  HZP_RESERVED_0B,
  HZP_RESERVED_0C,
  HZP_RESERVED_0D,
  HZP_RESERVED_0E,
  HZP_BYPASS,
  HZP_COUNT,
  HZP_INVALID(libademcoJNI.HZP_INVALID_get());

  public final int swigValue() {
    return swigValue;
  }

  public static HbZoneProperty swigToEnum(int swigValue) {
    HbZoneProperty[] swigValues = HbZoneProperty.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (HbZoneProperty swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + HbZoneProperty.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private HbZoneProperty() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private HbZoneProperty(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private HbZoneProperty(HbZoneProperty swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

