/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public interface libademcoConstants {
  public final static int ADEMCO_OK = libademcoJNI.ADEMCO_OK_get();
  public final static int ADEMCO_ERR = libademcoJNI.ADEMCO_ERR_get();
  public final static int ADEMCO_PACKET_ACCT_MAX_LEN = libademcoJNI.ADEMCO_PACKET_ACCT_MAX_LEN_get();
  public final static int ADEMCO_PACKET_DATA_SEGMENT_EMPTY_LEN = libademcoJNI.ADEMCO_PACKET_DATA_SEGMENT_EMPTY_LEN_get();
  public final static int ADEMCO_PACKET_DATA_SEGMENT_FULL_LEN = libademcoJNI.ADEMCO_PACKET_DATA_SEGMENT_FULL_LEN_get();
  public final static int ADEMCO_PACKET_DATA_SEGMENT_FULL_LEN_MAX = libademcoJNI.ADEMCO_PACKET_DATA_SEGMENT_FULL_LEN_MAX_get();
  public final static int ADEMCO_PACKET_MAX_LEN = libademcoJNI.ADEMCO_PACKET_MAX_LEN_get();
  public final static int CONGWIN_FE100_PACKET_LEN = libademcoJNI.CONGWIN_FE100_PACKET_LEN_get();
  public final static int ADEMCO_PACKET_TIMESTAMP_LEN = libademcoJNI.ADEMCO_PACKET_TIMESTAMP_LEN_get();
  public final static int ADEMCO_PACKET_XDATA_MAX_LEN = libademcoJNI.ADEMCO_PACKET_XDATA_MAX_LEN_get();
  public final static int ADEMCO_ID_MIN = libademcoJNI.ADEMCO_ID_MIN_get();
  public final static int ADEMCO_ID_MAX = libademcoJNI.ADEMCO_ID_MAX_get();
  public final static int ADEMCO_ID_SENTINEL = libademcoJNI.ADEMCO_ID_SENTINEL_get();
  public final static int ADEMCO_ZONE_FOR_MACHINE_SELF = libademcoJNI.ADEMCO_ZONE_FOR_MACHINE_SELF_get();
  public final static int ADEMCO_ZONE_MIN = libademcoJNI.ADEMCO_ZONE_MIN_get();
  public final static int ADEMCO_ZONE_MAX = libademcoJNI.ADEMCO_ZONE_MAX_get();
  public final static int ADEMCO_ZONE_SENTINEL = libademcoJNI.ADEMCO_ZONE_SENTINEL_get();
  public final static int ADEMCO_GG_MIN = libademcoJNI.ADEMCO_GG_MIN_get();
  public final static int ADEMCO_GG_MAX = libademcoJNI.ADEMCO_GG_MAX_get();
  public final static int ADEMCO_GG_SENTINEL = libademcoJNI.ADEMCO_GG_SENTINEL_get();
  public final static String ADEMCO_PACKET_ID_NULL = libademcoJNI.ADEMCO_PACKET_ID_NULL_get();
  public final static String ADEMCO_PACKET_ID_ACK = libademcoJNI.ADEMCO_PACKET_ID_ACK_get();
  public final static String ADEMCO_PACKET_ID_NAK = libademcoJNI.ADEMCO_PACKET_ID_NAK_get();
  public final static String ADEMCO_PACKET_ID_DUH = libademcoJNI.ADEMCO_PACKET_ID_DUH_get();
  public final static String ADEMCO_PACKET_ID_HB = libademcoJNI.ADEMCO_PACKET_ID_HB_get();
  public final static String ADEMCO_PACKET_ID_ADM_CID = libademcoJNI.ADEMCO_PACKET_ID_ADM_CID_get();
  public final static String ADEMCO_PACKET_ID_MOD_REG = libademcoJNI.ADEMCO_PACKET_ID_MOD_REG_get();
  public final static String ADEMCO_PACKET_ID_REG_RSP = libademcoJNI.ADEMCO_PACKET_ID_REG_RSP_get();
  public final static String ADEMCO_RRCVR_DEFAULT = libademcoJNI.ADEMCO_RRCVR_DEFAULT_get();
  public final static String ADEMCO_LPREF_DEFAULT = libademcoJNI.ADEMCO_LPREF_DEFAULT_get();
  public final static char ADEMCO_PACKET_PREFIX = libademcoJNI.ADEMCO_PACKET_PREFIX_get();
  public final static char ADEMCO_PACKET_SUFIX = libademcoJNI.ADEMCO_PACKET_SUFIX_get();
  public final static int HB_3SECTION_MACHINE_GG_MIN = libademcoJNI.HB_3SECTION_MACHINE_GG_MIN_get();
  public final static int HB_3SECTION_MACHINE_GG_MAX = libademcoJNI.HB_3SECTION_MACHINE_GG_MAX_get();
  public final static int HB_COM_DATA_MAX_LEN = libademcoJNI.HB_COM_DATA_MAX_LEN_get();
  public final static int HbComReq_A0_len = libademcoJNI.HbComReq_A0_len_get();
  public final static String HbComReq_A0_data = libademcoJNI.HbComReq_A0_data_get();
  public final static int HbComResp_A0_len = libademcoJNI.HbComResp_A0_len_get();
  public final static String HbComResp_A0_head = libademcoJNI.HbComResp_A0_head_get();
  public final static int HbComReq_A1_len = libademcoJNI.HbComReq_A1_len_get();
  public final static String HbComReq_A1_data = libademcoJNI.HbComReq_A1_data_get();
  public final static int HbComResp_A2_len_min = libademcoJNI.HbComResp_A2_len_min_get();
  public final static int HbComResp_A2_max_zone = libademcoJNI.HbComResp_A2_max_zone_get();
  public final static int HbComResp_A2_len_max = libademcoJNI.HbComResp_A2_len_max_get();
  public final static String HbComResp_A2_head = libademcoJNI.HbComResp_A2_head_get();
  public final static int HbComReq_A2_len = libademcoJNI.HbComReq_A2_len_get();
  public final static String HbComReq_A2_data = libademcoJNI.HbComReq_A2_data_get();
  public final static int HbComReq_A3_len = libademcoJNI.HbComReq_A3_len_get();
  public final static String HbComReq_A3_head = libademcoJNI.HbComReq_A3_head_get();
  public final static int HbComResp_A3_len = libademcoJNI.HbComResp_A3_len_get();
  public final static String HbComResp_A3_data = libademcoJNI.HbComResp_A3_data_get();
  public final static int HbComResp_A4_len = libademcoJNI.HbComResp_A4_len_get();
  public final static String HbComResp_A4_head = libademcoJNI.HbComResp_A4_head_get();
  public final static int HbComReq_A5_len = libademcoJNI.HbComReq_A5_len_get();
  public final static String HbComReq_A5_data = libademcoJNI.HbComReq_A5_data_get();
  public final static int HbComResp_A6_len = libademcoJNI.HbComResp_A6_len_get();
  public final static String HbComResp_A6_head = libademcoJNI.HbComResp_A6_head_get();
  public final static int HbComReq_A7_len = libademcoJNI.HbComReq_A7_len_get();
  public final static String HbComReq_A7_head = libademcoJNI.HbComReq_A7_head_get();
  public final static int HbComResp_A7_len = libademcoJNI.HbComResp_A7_len_get();
  public final static String HbComResp_A7_data = libademcoJNI.HbComResp_A7_data_get();
  public final static int HbComResp_A8_len = libademcoJNI.HbComResp_A8_len_get();
  public final static String HbComResp_A8_data = libademcoJNI.HbComResp_A8_data_get();
  public final static int HbComReq_AA_len = libademcoJNI.HbComReq_AA_len_get();
  public final static String HbComReq_AA_head = libademcoJNI.HbComReq_AA_head_get();
  public final static int HbComResp_AB_len = libademcoJNI.HbComResp_AB_len_get();
  public final static String HbComResp_AB_head = libademcoJNI.HbComResp_AB_head_get();
  public final static int HbComReq_AC_len = libademcoJNI.HbComReq_AC_len_get();
  public final static String HbComReq_AC_data = libademcoJNI.HbComReq_AC_data_get();
  public final static int HbComReq_AD_len = libademcoJNI.HbComReq_AD_len_get();
  public final static String HbComReq_AD_data = libademcoJNI.HbComReq_AD_data_get();
  public final static int HbComResp_AD_len_min = libademcoJNI.HbComResp_AD_len_min_get();
  public final static int HbComResp_AD_max_zone = libademcoJNI.HbComResp_AD_max_zone_get();
  public final static int HbComResp_AD_len_max = libademcoJNI.HbComResp_AD_len_max_get();
  public final static String HbComResp_AD_head = libademcoJNI.HbComResp_AD_head_get();
  public final static int HbComReq_AE_len = libademcoJNI.HbComReq_AE_len_get();
  public final static String HbComReq_AE_head = libademcoJNI.HbComReq_AE_head_get();
  public final static int HbComResp_AF_len = libademcoJNI.HbComResp_AF_len_get();
  public final static String HbComResp_AF_head = libademcoJNI.HbComResp_AF_head_get();
  public final static int HbComReq_B0_len = libademcoJNI.HbComReq_B0_len_get();
  public final static String HbComReq_B0_data = libademcoJNI.HbComReq_B0_data_get();
  public final static int HbComResp_B1_len = libademcoJNI.HbComResp_B1_len_get();
  public final static String HbComResp_B1_head = libademcoJNI.HbComResp_B1_head_get();
  public final static int HbComReq_RD_acct_len = libademcoJNI.HbComReq_RD_acct_len_get();
  public final static String HbComReq_RD_acct_data = libademcoJNI.HbComReq_RD_acct_data_get();
  public final static int HbComResp_RD_acct_len = libademcoJNI.HbComResp_RD_acct_len_get();
  public final static String HbComResp_RD_acct_head = libademcoJNI.HbComResp_RD_acct_head_get();
  public final static int HbComReq_WR_acct_len = libademcoJNI.HbComReq_WR_acct_len_get();
  public final static String HbComReq_WR_acct_head = libademcoJNI.HbComReq_WR_acct_head_get();
  public final static int HbComResp_WR_acct_len = libademcoJNI.HbComResp_WR_acct_len_get();
  public final static String HbComResp_WR_acct_head = libademcoJNI.HbComResp_WR_acct_head_get();
}
