/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public enum AdemcoEvent {
  EVENT_INVALID_EVENT(libademcoJNI.EVENT_INVALID_EVENT_get()),
  EVENT_ARM(libademcoJNI.EVENT_ARM_get()),
  EVENT_DISARM(libademcoJNI.EVENT_DISARM_get()),
  EVENT_HALFARM_1456(libademcoJNI.EVENT_HALFARM_1456_get()),
  EVENT_HALFARM(libademcoJNI.EVENT_HALFARM_get()),
  EVENT_EMERGENCY(libademcoJNI.EVENT_EMERGENCY_get()),
  EVENT_BURGLAR(libademcoJNI.EVENT_BURGLAR_get()),
  EVENT_DOORRINGING(libademcoJNI.EVENT_DOORRINGING_get()),
  EVENT_FIRE(libademcoJNI.EVENT_FIRE_get()),
  EVENT_DURESS(libademcoJNI.EVENT_DURESS_get()),
  EVENT_GAS(libademcoJNI.EVENT_GAS_get()),
  EVENT_WATER(libademcoJNI.EVENT_WATER_get()),
  EVENT_TAMPER(libademcoJNI.EVENT_TAMPER_get()),
  EVENT_ZONE_TAMPER(libademcoJNI.EVENT_ZONE_TAMPER_get()),
  EVENT_BYPASS(libademcoJNI.EVENT_BYPASS_get()),
  EVENT_BYPASS_RESUME(libademcoJNI.EVENT_BYPASS_RESUME_get()),
  EVENT_AC_BROKE(libademcoJNI.EVENT_AC_BROKE_get()),
  EVENT_AC_RECOVER(libademcoJNI.EVENT_AC_RECOVER_get()),
  EVENT_LOWBATTERY(libademcoJNI.EVENT_LOWBATTERY_get()),
  EVENT_BATTERY_RECOVER(libademcoJNI.EVENT_BATTERY_RECOVER_get()),
  EVENT_BADBATTERY(libademcoJNI.EVENT_BADBATTERY_get()),
  EVENT_BADBATTERY_RECOVER(libademcoJNI.EVENT_BADBATTERY_RECOVER_get()),
  EVENT_SOLARDISTURB(libademcoJNI.EVENT_SOLARDISTURB_get()),
  EVENT_SOLARDISTURB_RECOVER(libademcoJNI.EVENT_SOLARDISTURB_RECOVER_get()),
  EVENT_DISCONNECT(libademcoJNI.EVENT_DISCONNECT_get()),
  EVENT_RECONNECT(libademcoJNI.EVENT_RECONNECT_get()),
  EVENT_BATTERY_EXCEPTION(libademcoJNI.EVENT_BATTERY_EXCEPTION_get()),
  EVENT_BATTERY_EXCEPTION_RECOVER(libademcoJNI.EVENT_BATTERY_EXCEPTION_RECOVER_get()),
  EVENT_OTHER_EXCEPTION(libademcoJNI.EVENT_OTHER_EXCEPTION_get()),
  EVENT_OTHER_EXCEPTION_RECOVER(libademcoJNI.EVENT_OTHER_EXCEPTION_RECOVER_get()),
  EVENT_LOST(libademcoJNI.EVENT_LOST_get()),
  EVENT_LOST_RECOVER(libademcoJNI.EVENT_LOST_RECOVER_get()),
  EVENT_3100(libademcoJNI.EVENT_3100_get()),
  EVENT_SERIAL485DIS(libademcoJNI.EVENT_SERIAL485DIS_get()),
  EVENT_SERIAL485CONN(libademcoJNI.EVENT_SERIAL485CONN_get()),
  EVENT_CONN_HANGUP(libademcoJNI.EVENT_CONN_HANGUP_get()),
  EVENT_CONN_RESUME(libademcoJNI.EVENT_CONN_RESUME_get()),
  EVENT_DISARM_PWD_ERR(libademcoJNI.EVENT_DISARM_PWD_ERR_get()),
  EVENT_SUB_MACHINE_SENSOR_EXCEPTION(libademcoJNI.EVENT_SUB_MACHINE_SENSOR_EXCEPTION_get()),
  EVENT_SUB_MACHINE_SENSOR_RESUME(libademcoJNI.EVENT_SUB_MACHINE_SENSOR_RESUME_get()),
  EVENT_SUB_MACHINE_POWER_EXCEPTION(libademcoJNI.EVENT_SUB_MACHINE_POWER_EXCEPTION_get()),
  EVENT_SUB_MACHINE_POWER_RESUME(libademcoJNI.EVENT_SUB_MACHINE_POWER_RESUME_get()),
  EVENT_COM_PASSTHROUGH(libademcoJNI.EVENT_COM_PASSTHROUGH_get()),
  EVENT_ENTER_SET_MODE(libademcoJNI.EVENT_ENTER_SET_MODE_get()),
  EVENT_EXIT_SET_MODE(libademcoJNI.EVENT_EXIT_SET_MODE_get()),
  EVENT_QUERY_SUB_MACHINE(libademcoJNI.EVENT_QUERY_SUB_MACHINE_get()),
  EVENT_WRITE_TO_MACHINE(libademcoJNI.EVENT_WRITE_TO_MACHINE_get()),
  EVENT_I_AM_NET_MODULE(libademcoJNI.EVENT_I_AM_NET_MODULE_get()),
  EVENT_I_AM_GPRS(libademcoJNI.EVENT_I_AM_GPRS_get()),
  EVENT_I_AM_LCD_MACHINE(libademcoJNI.EVENT_I_AM_LCD_MACHINE_get()),
  EVENT_I_AM_WIRE_MACHINE(libademcoJNI.EVENT_I_AM_WIRE_MACHINE_get()),
  EVENT_I_AM_WIFI_MACHINE(libademcoJNI.EVENT_I_AM_WIFI_MACHINE_get()),
  EVENT_I_AM_3_SECTION_MACHINE(libademcoJNI.EVENT_I_AM_3_SECTION_MACHINE_get()),
  EVENT_I_AM_IOT_MACHINE(libademcoJNI.EVENT_I_AM_IOT_MACHINE_get()),
  EVENT_I_AM_TRUE_COLOR(libademcoJNI.EVENT_I_AM_TRUE_COLOR_get()),
  EVENT_I_AM_GPRS_IOT(libademcoJNI.EVENT_I_AM_GPRS_IOT_get()),
  EVENT_I_AM_GPRS_PHONE(libademcoJNI.EVENT_I_AM_GPRS_PHONE_get()),
  EVENT_I_AM_NB_MACHINE(libademcoJNI.EVENT_I_AM_NB_MACHINE_get()),
  EVENT_PHONE_USER_SOS(libademcoJNI.EVENT_PHONE_USER_SOS_get()),
  EVENT_PHONE_USER_CANCLE_ALARM(libademcoJNI.EVENT_PHONE_USER_CANCLE_ALARM_get()),
  EVENT_ENTER_SETTING_MODE(libademcoJNI.EVENT_ENTER_SETTING_MODE_get()),
  EVENT_EXIT_SETTING_MODE(libademcoJNI.EVENT_EXIT_SETTING_MODE_get()),
  EVENT_RESTORE_FACTORY_SETTINGS_710(libademcoJNI.EVENT_RESTORE_FACTORY_SETTINGS_710_get()),
  EVENT_RESTORE_FACTORY_SETTINGS(libademcoJNI.EVENT_RESTORE_FACTORY_SETTINGS_get()),
  EVENT_SIM_IS_IOT_CARD(libademcoJNI.EVENT_SIM_IS_IOT_CARD_get()),
  EVENT_SIM_IS_IOT_PLATFORM_CARD(libademcoJNI.EVENT_SIM_IS_IOT_PLATFORM_CARD_get()),
  EVENT_SIM_IS_NOT_IOT_CARD(libademcoJNI.EVENT_SIM_IS_NOT_IOT_CARD_get()),
  EVENT_WHAT_IS_YOUR_TYPE(libademcoJNI.EVENT_WHAT_IS_YOUR_TYPE_get()),
  EVENT_SIGNAL_STRENGTH_CHANGED(libademcoJNI.EVENT_SIGNAL_STRENGTH_CHANGED_get()),
  EVENT_OFFLINE(libademcoJNI.EVENT_OFFLINE_get()),
  EVENT_ONLINE(libademcoJNI.EVENT_ONLINE_get());

  public final int swigValue() {
    return swigValue;
  }

  public static AdemcoEvent swigToEnum(int swigValue) {
    AdemcoEvent[] swigValues = AdemcoEvent.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AdemcoEvent swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AdemcoEvent.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AdemcoEvent() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AdemcoEvent(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AdemcoEvent(AdemcoEvent swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

