/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public class AdemcoXDataSegment {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AdemcoXDataSegment(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AdemcoXDataSegment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libademcoJNI.delete_AdemcoXDataSegment(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLenghFormat(AdemcoXDataLengthFormat value) {
    libademcoJNI.AdemcoXDataSegment_lenghFormat_set(swigCPtr, this, value.swigValue());
  }

  public AdemcoXDataLengthFormat getLenghFormat() {
    return AdemcoXDataLengthFormat.swigToEnum(libademcoJNI.AdemcoXDataSegment_lenghFormat_get(swigCPtr, this));
  }

  public void setRaw(byte[] value) {
    libademcoJNI.AdemcoXDataSegment_raw_set(swigCPtr, this, value);
  }

  public byte[] getRaw() {
    return libademcoJNI.AdemcoXDataSegment_raw_get(swigCPtr, this);
  }

  public void setRaw_len(int value) {
    libademcoJNI.AdemcoXDataSegment_raw_len_set(swigCPtr, this, value);
  }

  public int getRaw_len() {
    return libademcoJNI.AdemcoXDataSegment_raw_len_get(swigCPtr, this);
  }

  public AdemcoXDataSegment() {
    this(libademcoJNI.new_AdemcoXDataSegment(), true);
  }

}
