/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public enum AdemcoEventLevel {
  EVENT_LEVEL_NULL,
  EVENT_LEVEL_STATUS,
  EVENT_LEVEL_EXCEPTION_RESUME,
  EVENT_LEVEL_EXCEPTION,
  EVENT_LEVEL_ALARM;

  public final int swigValue() {
    return swigValue;
  }

  public static AdemcoEventLevel swigToEnum(int swigValue) {
    AdemcoEventLevel[] swigValues = AdemcoEventLevel.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (AdemcoEventLevel swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + AdemcoEventLevel.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private AdemcoEventLevel() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private AdemcoEventLevel(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private AdemcoEventLevel(AdemcoEventLevel swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

