/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public enum HbComResp_AD_p1 {
  HbComResp_AD_p1_single(libademcoJNI.HbComResp_AD_p1_single_get()),
  HbComResp_AD_p1_double(libademcoJNI.HbComResp_AD_p1_double_get());

  public final int swigValue() {
    return swigValue;
  }

  public static HbComResp_AD_p1 swigToEnum(int swigValue) {
    HbComResp_AD_p1[] swigValues = HbComResp_AD_p1.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (HbComResp_AD_p1 swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + HbComResp_AD_p1.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private HbComResp_AD_p1() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private HbComResp_AD_p1(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private HbComResp_AD_p1(HbComResp_AD_p1 swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

