/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public class HbComData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HbComData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HbComData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libademcoJNI.delete_HbComData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(byte[] value) {
    libademcoJNI.HbComData_data_set(swigCPtr, this, value);
  }

  public byte[] getData() {
    return libademcoJNI.HbComData_data_get(swigCPtr, this);
  }

  public void setLen(int value) {
    libademcoJNI.HbComData_len_set(swigCPtr, this, value);
  }

  public int getLen() {
    return libademcoJNI.HbComData_len_get(swigCPtr, this);
  }

  public HbComData() {
    this(libademcoJNI.new_HbComData(), true);
  }

}
