/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public enum HbComResponseType {
  HbComResp_A0,
  HbComResp_A2,
  HbComResp_A3,
  HbComResp_A4,
  HbComResp_A6,
  HbComResp_A7,
  HbComResp_A8,
  HbComResp_A9,
  HbComResp_AB,
  HbComResp_AD,
  HbComResp_AF,
  HbComResp_B1,
  HbComResp_Invalid(libademcoJNI.HbComResp_Invalid_get());

  public final int swigValue() {
    return swigValue;
  }

  public static HbComResponseType swigToEnum(int swigValue) {
    HbComResponseType[] swigValues = HbComResponseType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (HbComResponseType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + HbComResponseType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private HbComResponseType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private HbComResponseType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private HbComResponseType(HbComResponseType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

