/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public enum HbComRequestType {
  HbComReq_A0,
  HbComReq_A1,
  HbComReq_A2,
  HbComReq_A3,
  HbComReq_A5,
  HbComReq_A7,
  HbComReq_A9,
  HbComReq_AA,
  HbComReq_AC,
  HbComReq_AD,
  HbComReq_AE,
  HbComReq_B0,
  HbComReq_RD_acct,
  HbComReq_WR_acct,
  HbComReq_Invalid(libademcoJNI.HbComReq_Invalid_get());

  public final int swigValue() {
    return swigValue;
  }

  public static HbComRequestType swigToEnum(int swigValue) {
    HbComRequestType[] swigValues = HbComRequestType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (HbComRequestType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + HbComRequestType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private HbComRequestType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private HbComRequestType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private HbComRequestType(HbComRequestType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

