/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public enum HbComResp_A4_p3 {
  HbComResp_A4_p3_fail(libademcoJNI.HbComResp_A4_p3_fail_get()),
  HbComResp_A4_p3_ok(libademcoJNI.HbComResp_A4_p3_ok_get()),
  HbComResp_A4_p3_dup(libademcoJNI.HbComResp_A4_p3_dup_get()),
  HbComResp_A4_p3_ne(libademcoJNI.HbComResp_A4_p3_ne_get());

  public final int swigValue() {
    return swigValue;
  }

  public static HbComResp_A4_p3 swigToEnum(int swigValue) {
    HbComResp_A4_p3[] swigValues = HbComResp_A4_p3.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (HbComResp_A4_p3 swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + HbComResp_A4_p3.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private HbComResp_A4_p3() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private HbComResp_A4_p3(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private HbComResp_A4_p3(HbComResp_A4_p3 swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

