/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public enum HbMachineType {
  HMT_WIFI,
  HMT_CAMERA,
  HMT_GPRS_IOT,
  HMT_NETMOD,
  HMT_GPRS,
  HMT_LCD,
  HMT_WIRED,
  HMT_TRUE_COLOR,
  HMT_3_SECTION,
  HMT_IOT,
  HMT_GPRS_PHONE,
  HMT_NB,
  HMT_COUNT,
  HMT_INVALID(libademcoJNI.HMT_INVALID_get());

  public final int swigValue() {
    return swigValue;
  }

  public static HbMachineType swigToEnum(int swigValue) {
    HbMachineType[] swigValues = HbMachineType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (HbMachineType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + HbMachineType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private HbMachineType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private HbMachineType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private HbMachineType(HbMachineType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

