/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.hb3344.ademco;

public class HbMachineTimer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HbMachineTimer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HbMachineTimer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libademcoJNI.delete_HbMachineTimer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTimer(HbTimer value) {
    libademcoJNI.HbMachineTimer_timer_set(swigCPtr, this, HbTimer.getCPtr(value), value);
  }

  public HbTimer getTimer() {
    long cPtr = libademcoJNI.HbMachineTimer_timer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new HbTimer(cPtr, false);
  }

  public void setData(byte[] value) {
    libademcoJNI.HbMachineTimer_data_set(swigCPtr, this, value);
  }

  public byte[] getData() {
    return libademcoJNI.HbMachineTimer_data_get(swigCPtr, this);
  }

  public HbMachineTimer() {
    this(libademcoJNI.new_HbMachineTimer(), true);
  }

}
